### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by itomek** [HopDizzle/NET-FantasyData#1]

**Comment by HopDizzle** [comment]
I'm still in the process of completing the library, but I'll definitely work to make this a nuget package ASAP.

**Comment by HopDizzle** [comment]
The library is still in the infancy of development, but I have added a nuget package to nuget.org.

https://www.nuget.org/packages/FantasyData/

**Comment by itomek** [comment]
awesome thanks much! I will check it out soon.
